name: sq_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.6.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  get_it: ^8.0.3
  sqflite: ^2.4.1
  easy_localization: ^3.0.7+1
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  permission_handler: ^12.0.1
  hydrated_bloc: ^10.1.0
  intl: ^0.19.0
  path: ^1.9.0
  path_provider: ^2.1.5
  crypto: ^3.0.6
  flutter_screenutil: ^5.9.3
  croppy: ^1.3.6
  toastification: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/icons/
    - assets/loading/
    - assets/fonts/
    - assets/lang/


  fonts:
    - family: Black
      fonts:
        - asset: assets/fonts/Cairo-Black.ttf
    - family: ExtraBold
      fonts:
        - asset: assets/fonts/Cairo-ExtraBold.ttf
    - family: CairoBold
      fonts:
        - asset: assets/fonts/Cairo-Bold.ttf
    - family: CairoRegular
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
    - family: CairoSemiBold
      fonts:
        - asset: assets/fonts/Cairo-SemiBold.ttf
